config/routes.rb
Demo3::Application.routes.draw do
  resources :add_statuses

  resources :posts

  root :to => 'posts#index'

end

app/models/add_status.rb
class AddStatus < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/add_statuses_controller.rb
class AddStatusesController < ApplicationController
  # GET /add_statuses
  # GET /add_statuses.json
  def index
    @add_statuses = AddStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @add_statuses }
    end
  end

  # GET /add_statuses/1
  # GET /add_statuses/1.json
  def show
    @add_status = AddStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @add_status }
    end
  end

  # GET /add_statuses/new
  # GET /add_statuses/new.json
  def new
    @add_status = AddStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @add_status }
    end
  end

  # GET /add_statuses/1/edit
  def edit
    @add_status = AddStatus.find(params[:id])
  end

  # POST /add_statuses
  # POST /add_statuses.json
  def create
    @add_status = AddStatus.new(params[:add_status])

    respond_to do |format|
      if @add_status.save
        format.html { redirect_to @add_status, :notice => 'Add status was successfully created.' }
        format.json { render :json => @add_status, :status => :created, :location => @add_status }
      else
        format.html { render :action => "new" }
        format.json { render :json => @add_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /add_statuses/1
  # PUT /add_statuses/1.json
  def update
    @add_status = AddStatus.find(params[:id])

    respond_to do |format|
      if @add_status.update_attributes(params[:add_status])
        format.html { redirect_to @add_status, :notice => 'Add status was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @add_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /add_statuses/1
  # DELETE /add_statuses/1.json
  def destroy
    @add_status = AddStatus.find(params[:id])
    @add_status.destroy

    respond_to do |format|
      format.html { redirect_to add_statuses_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController # GET /posts
  respond_to :html
  before_filter :get_post, :except => [:index, :create]

  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.save
    flash[:notice] = "Added succesfully"
    respond_with(@post)
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])
    flash[:notice] = "Updated succesfully"
    respond_with(@post)
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_with(@post)
  end

  private
    def get_post
      @post = params[:id].present? ? Post.find(params[:id]) : Post.new
    end
end

app/helpers/add_statuses_helper.rb
module AddStatusesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pretty_date(date)
    date.strftime("%B %d %Y")
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def author_first_last(post)
    "#{post.author_first} #{post.author_last}"
  end

  def should_show?(post)
    post.status == "published"
  end
end

app/views/add_statuses/_form.html.erb
<%= form_for(@add_status) do |f| %>
  <% if @add_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@add_status.errors.count, "error") %> prohibited this add_status from being saved:</h2>

      <ul>
      <% @add_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/add_statuses/edit.html.erb
<h1>Editing add_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @add_status %> |
<%= link_to 'Back', add_statuses_path %>

app/views/add_statuses/index.html.erb
<h1>Listing add_statuses</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @add_statuses.each do |add_status| %>
  <tr>
    <td><%= link_to 'Show', add_status %></td>
    <td><%= link_to 'Edit', edit_add_status_path(add_status) %></td>
    <td><%= link_to 'Destroy', add_status, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Add status', new_add_status_path %>

app/views/add_statuses/new.html.erb
<h1>New add_status</h1>

<%= render 'form' %>

<%= link_to 'Back', add_statuses_path %>

app/views/add_statuses/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_add_status_path(@add_status) %> |
<%= link_to 'Back', add_statuses_path %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Demo3
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/posts/_category_list.html.erb
<h2>Categories</h2>
<%categories.each do |c|%>
<li><a href="#"><%=c%></a></li>
<%end%>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :status%><br />
    <%= f.text_field :status%>
  </div>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :author_first %><br />
    <%= f.text_field :author_first%>
  </div>
  <div class="field">
    <%= f.label :author_last %><br />
    <%= f.text_field :author_last %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_green_box.html.erb
<div style="border:4px solid #cccc99;padding:30px">
  <%= yield %>
</div>

app/views/posts/_post.html.haml
- if(should_show?(post))
  %h3= post.title
  %i #{author_first_last(post)} #{pretty_date(post.created_at)}
  %hr
  = link_to 'Show', post
  = link_to 'Edit', edit_post_path(post)
  = link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.haml
%h1 Listing posts
= render :partial => 'post', :collection => @posts
%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>

<p>
  <b>Author First:</b>
  <%= @post.author_first%>
</p>
<p>
  <b>Author Last:</b>
  <%= @post.author_last%>
</p>




<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>